In [4]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv("Tr_ev_fiyatlari_v2.csv")

In [7]:
data.head()

,fiyat,alan,yatak_odasi,banyo_sayisi,kat_sayisi,anayol_baglanti,misafir_odası,bodrum,sıcak_su,klima,otopark,mob_drm
0,13300000,7420,4,2,3,evet,hayır,hayır,hayır,evet,2,mobilyalı
1,12250000,8960,4,4,4,evet,hayır,hayır,hayır,evet,3,mobilyalı
2,12250000,9960,3,2,2,evet,hayır,evet,hayır,hayır,2,yarı mobilyalı
3,12215000,7500,4,2,2,evet,hayır,evet,hayır,evet,3,mobilyalı
4,11410000,7420,4,1,2,evet,evet,evet,hayır,evet,2,mobilyalı